server.port=${SERVER_PORT:8080}
spring.application.name=alertas-bff

ms.alertas.url=${MS_ALERTAS_URL:http://localhost:8081}

spring.security.oauth2.resourceserver.jwt.issuer-uri=XXXX
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=XXXXX

azure.ad.b2c.client-id=${AZURE_AD_B2C_CLIENT_ID:XXXX}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
