server.port=${SERVER_PORT:8080}
spring.application.name=alertas-bff

ms.alertas.url=${MS_ALERTAS_URL:http://localhost:8081}

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cn01duoc2026.b2clogin.com/18dffa37-dc2c-4aac-a322-05bbe323a686/v2.0/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cn01duoc2026.b2clogin.com/18dffa37-dc2c-4aac-a322-05bbe323a686/discovery/v2.0/keys?p=B2C_1_cn1_login

azure.ad.b2c.client-id=${AZURE_AD_B2C_CLIENT_ID:7103a40c-5cf9-42dd-afb9-0a6811a014ef}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html