-- Script base para Oracle Autonomous Database / Oracle Cloud
-- Ejecutar en SQL Developer Web antes de probar el backend si no se usa ddl-auto=update.

CREATE SEQUENCE SEQ_PACIENTES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SIGNALS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ALERTAS START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE PACIENTES (
  ID NUMBER PRIMARY KEY,
  NOMBRE VARCHAR2(100) NOT NULL,
  APELLIDO VARCHAR2(100) NOT NULL,
  FECHA_NACIMIENTO DATE,
  RUT VARCHAR2(12) UNIQUE,
  HABITACION VARCHAR2(20),
  DIAGNOSTICO VARCHAR2(500),
  ESTADO VARCHAR2(20) DEFAULT 'ACTIVO'
);

CREATE TABLE SIGNALS_VITALES (
  ID NUMBER PRIMARY KEY,
  PACIENTE_ID NUMBER NOT NULL,
  FRECUENCIA_CARDIACA NUMBER,
  PRESION_SISTOLICA NUMBER,
  PRESION_DIASTOLICA NUMBER,
  TEMPERATURA NUMBER(5,2),
  SATURACION_OXIGENO NUMBER,
  FRECUENCIA_RESPIRATORIA NUMBER,
  FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CRITICO NUMBER(1) DEFAULT 0,
  CONSTRAINT FK_SIGNALS_PACIENTE FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTES(ID)
);

CREATE TABLE ALERTAS (
  ID NUMBER PRIMARY KEY,
  PACIENTE_ID NUMBER NOT NULL,
  SIGNAL_ID NUMBER,
  TIPO VARCHAR2(50) NOT NULL,
  DESCRIPCION VARCHAR2(500),
  SEVERIDAD VARCHAR2(20),
  ESTADO VARCHAR2(20) DEFAULT 'ACTIVA',
  FECHA_ALERTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FECHA_ATENCION TIMESTAMP,
  CONSTRAINT FK_ALERTAS_PACIENTE FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTES(ID),
  CONSTRAINT FK_ALERTAS_SIGNAL FOREIGN KEY (SIGNAL_ID) REFERENCES SIGNALS_VITALES(ID)
);

INSERT INTO PACIENTES (ID, NOMBRE, APELLIDO, FECHA_NACIMIENTO, RUT, HABITACION, DIAGNOSTICO, ESTADO)
VALUES (SEQ_PACIENTES.NEXTVAL, 'Juan', 'Pérez', DATE '1970-04-12', '12345678-9', 'UCI-01', 'Paciente crítico en observación', 'ACTIVO');

COMMIT;
